language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE palettepicker_test;' -U postgres
- npm run migrate:test
- npm run seed:test
notifications:
  email: false
before_deploy:
  - heroku run 'knex migrate:latest'
  - heroku run 'knex seed:run'
deploy:
  provider: heroku
  api_key:
    secure: HLDcXbcJ9yrSdrJ26OUMY1IK2ehnELXsc0FNk2zE7FPERIWcjqVRnwN0kUyC3FRdRcTFs/65NyOpB5IPwNADzBb3/cVJTZ0H9qZNCS6BWM1cklHOteNfq5q3ucJ/K6pDeq+CMP1aYgGfofkRUq/GTx41lhh9PJWTCW2Zv6DbTKfaDN4qth0mN/woAssKGl2lqORFv6bkeGjTwFLlehE/Ds/HTPaCuEo/A59Hw+/z1g+16Y6c9sEsM5Dbi//2zzFYFgQBKf0nBVDdX2+jz8buQL/96M1ym92leclr8tKkOw+aUx/B08gJLVyAPhKilo2iWhBGoe44zgiGC3ci5bzBPaqk553d+WpyYNrRCPxMNxDmBSgSnPsgtLgZktbcmz8B649JqZYDOCc00rmEfCDgE+A/K0JYyZjTqPa5JltgcyNTtqf5xaaQwuaZamIuyJy3fgH+MP5/XrXoP4QKdzVPPavHi4vUINrBJwBsCA7m7SaNmgZG0FFO2+fAo0p2QM4PN6aHQxSmirCAK/7Xw1Cw+2r7Dy5jEcOmnKMUzbd7SJdnS56nUar/elJMsGxKQzTJn6yENmKKqTlzn0NaOv4CphYIG0yamu7crxbc0hPbc+/AF+YK5Gyi0taqbhqx+6IC9H1jZtlvkLquOmNeMIzsVbD3RS4ial94+bowXsQUSQY=
  app: palette-picker-be
  skip_cleanup: true