language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE palettepicker_test;' -U postgres
- npm run migrate:test
- npm run seed:test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: nIUsKGq6E5Hm8rP2ta0pK3YCERQO3hje8qgnodm5h34cOV0NOSr9Ecz69qUP/TPD0f3QZjECqz6XEUv7ZwZCSiISpveLpkdqMoyKBzOGTsKBrtf6ZXrqCrRaAj2GKCYoa47CibPtCaWLMhp5hNGyn2tn6yKPcWHOxtbxQaNW9luEpuDHFzUdfF6frGFxhBR8YWapApJCLDXzM7qCctW3gNNMwo/KElNavICAtPT+a3prgMJF9yVmfPJVKe99P1K6UNv0HAUgp689Ep4BErX8r8j0k0RNSInJXgUWBPKcJJDqu4x6EkOavGBKwFGde+v7AxQZJE8lLKXABov7Kgm5ZmrY/gXjN+zvy8yYlnJFQj5UYVxJvBBamv5Q07sCrF+dmGwcKXkkiwIp3BeqZrY5S6GAhXKwCK2pZFQwS6NKXQuGJB9xwtDNRnHr96+49c1vPXkzh0/ejYNskzJw1UTAIezJhnYL+nEcI4SiZCaC3MyzRcrX3khR0BWzUTJ242/sW6kyVKnBlBj8hoSFOZRIFE/kmAUR72IO4RPpk3hN70uyhxsIcNOWFaDeHQH4xp6g62gzu4IGXoHRQQzGG8AhUvRlIRsV5iGK3PPiC8VfYSjEq69Em3sxHDIHm0tfnoT46+R5Q609owCapwx2txLLPNy6Xo/ef21nEY/JuzK2iYI=
  app: palette-picker-be
  skip_cleanup: true
